### ISSUE TITLE
teardown traceback on some connections

### ISSUE THREAD

**Issue by isi-mfurer** [emc-isilon/pike#125]
```
masen@mf-mbp12-wifi pike % ./.tox/py310/bin/python
Python 3.10.8 (main, Oct 13 2022, 10:19:13) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pike import TreeConnect, smb2
>>> tc = TreeConnect(server="localhost", creds="testuser%123Abc", share="share")
>>> tc()
TreeConnect(_client=None, server='localhost', port=445, creds='testuser%123Abc', share='share', resume=None, signing=False, encryption=False, require_dialect=None, require_capabilities=None, require_share_capabilities=None, conn=<pike.model.Connection object at 0x10c539720>, chan=<pike.model.Channel object at 0x10cceac50>, tree=<pike.model.Tree object at 0x10cd000d0>)
>>> 
Exception ignored in: <function TreeConnect.__del__ at 0x10ccbc8b0>
Traceback (most recent call last):
  File "/Users/masen/code/pike/pike/test/__init__.py", line 416, in __del__
  File "/Users/masen/code/pike/pike/test/__init__.py", line 375, in close
  File "/Users/masen/code/pike/pike/model.py", line 1394, in tree_disconnect
  File "/Users/masen/code/pike/pike/model.py", line 973, in transceive
  File "/Users/masen/code/pike/pike/model.py", line 973, in <listcomp>
  File "/Users/masen/code/pike/pike/model.py", line 238, in result
  File "/Users/masen/code/pike/.tox/py310/lib/python3.10/site-packages/future/utils/__init__.py", line 441, in raise_
  File "/Users/masen/code/pike/pike/model.py", line 816, in _prepare_outgoing
  File "/Users/masen/code/pike/pike/core.py", line 562, in serialize
  File "/Users/masen/code/pike/pike/core.py", line 551, in encode
  File "/Users/masen/code/pike/pike/netbios.py", line 57, in _encode
  File "/Users/masen/code/pike/pike/core.py", line 551, in encode
  File "/Users/masen/code/pike/pike/smb2.py", line 228, in _encode
  File "/Users/masen/code/pike/pike/digest.py", line 49, in aes128_cmac
  File "/Users/masen/code/pike/.tox/py310/lib/python3.10/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
KeyError: 'Cryptodome.Cipher.AES'
```

likely introduced with #72, more investigation needed before release 0.4.0

**Comment by isi-mfurer** [comment]
Seems to be a "using things in `__del__`" issue, deferring for the moment.
